name: Release

on:
  workflow_call:
    secrets:
      NPM_TOKEN:
        required: true
      RELEASE_TOKEN:
        required: true

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    runs-on: ubuntu-latest
    if: ${{ github.event.repository.is_template == false && !contains(github.repository, 'template') }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.20.0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '24.x'
          cache: pnpm
          registry-url: "https://registry.npmjs.org"

      - run: pnpm -v

      - name: Install deps
        run: pnpm install --frozen-lockfile

      - name: Skip if template
        id: skipcheck
        run: |
          if grep -q "@<your-scope>/<name>" package.json; then
            echo "Template placeholder detected â€” skipping release validation."
            echo "skip=true" >> $GITHUB_OUTPUT
          fi

      - name: Validate
        if: ${{ steps.skipcheck.outputs.skip != 'true' }}
        run: pnpm -w validate

      - name: Create Release PR or Publish to npm
        if: ${{ steps.skipcheck.outputs.skip != 'true' && success() }}
        uses: changesets/action@v1
        with:
          publish: pnpm -w changeset publish --access public
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}